//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footstep.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Footstep.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The acessory is required.
        /// </summary>
        public static string ACESSORY_REQUIRED {
            get {
                return ResourceManager.GetString("ACESSORY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Author id cannot be empty.
        /// </summary>
        public static string AUTHOR_ID_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("AUTHOR_ID_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The avataroverprofile is required.
        /// </summary>
        public static string AVATAROVERPROFILE_REQUIRED {
            get {
                return ResourceManager.GetString("AVATAROVERPROFILE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The bag is required.
        /// </summary>
        public static string BAG_REQUIRED {
            get {
                return ResourceManager.GetString("BAG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comment cannot be empty.
        /// </summary>
        public static string COMMENT_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("COMMENT_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comment not found.
        /// </summary>
        public static string COMMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Creation date cannot be past.
        /// </summary>
        public static string DATE_OF_CREATION_IN_THE_PAST {
            get {
                return ResourceManager.GetString("DATE_OF_CREATION_IN_THE_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The description is required.
        /// </summary>
        public static string DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This email is already registered.
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email cannot be empty.
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid email.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email or password invalid.
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Followed user Id cannot be null.
        /// </summary>
        public static string FOLLOWED_USER_ID_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("FOLLOWED_USER_ID_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Follower Id cannot be null.
        /// </summary>
        public static string FOLLOWER_ID_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("FOLLOWER_ID_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The heads is required.
        /// </summary>
        public static string HEAD_REQUIRED {
            get {
                return ResourceManager.GetString("HEAD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Latitude must be between -90 and 90.
        /// </summary>
        public static string INVALID_LATITUDE {
            get {
                return ResourceManager.GetString("INVALID_LATITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Longitude must be between -180 and 180.
        /// </summary>
        public static string INVALID_LONGITUDE {
            get {
                return ResourceManager.GetString("INVALID_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password must contain at least 8 characters and include at least one capital letter.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user is already following.
        /// </summary>
        public static string IS_FOLLOWING {
            get {
                return ResourceManager.GetString("IS_FOLLOWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Latitude is required.
        /// </summary>
        public static string LATITUDE_REQUIRED {
            get {
                return ResourceManager.GetString("LATITUDE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The leg is required.
        /// </summary>
        public static string LEG_REQUIRED {
            get {
                return ResourceManager.GetString("LEG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Longitude is required.
        /// </summary>
        public static string LONGITUDE_REQUIRED {
            get {
                return ResourceManager.GetString("LONGITUDE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The mapstyle is required.
        /// </summary>
        public static string MAPSTYLE_REQUIRED {
            get {
                return ResourceManager.GetString("MAPSTYLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name cannot be empty.
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name is required.
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parent id cannot be empty.
        /// </summary>
        public static string PARENT_ID_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("PARENT_ID_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parent not found.
        /// </summary>
        public static string PARENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PARENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Point of interest not found.
        /// </summary>
        public static string POINT_OF_INTEREST_NOT_FOUND {
            get {
                return ResourceManager.GetString("POINT_OF_INTEREST_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The pointofintereststyle is required.
        /// </summary>
        public static string POINTOFINTERESTSTYLE_REQUIRED {
            get {
                return ResourceManager.GetString("POINTOFINTERESTSTYLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The expiration date cannot be in the past.
        /// </summary>
        public static string THE_EXPIRATION_DATE_CANNOT_BE_IN_THE_PAST {
            get {
                return ResourceManager.GetString("THE_EXPIRATION_DATE_CANNOT_BE_IN_THE_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This user does not follow anyone.
        /// </summary>
        public static string THIS_USER_DOES_NOT_FOLLOW_ANYONE {
            get {
                return ResourceManager.GetString("THIS_USER_DOES_NOT_FOLLOW_ANYONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This user has no followers.
        /// </summary>
        public static string THIS_USER_HAS_NO_FOLLOWERS {
            get {
                return ResourceManager.GetString("THIS_USER_HAS_NO_FOLLOWERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The torso is required.
        /// </summary>
        public static string TORSO_REQUIRED {
            get {
                return ResourceManager.GetString("TORSO_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Trace not found.
        /// </summary>
        public static string TRACE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRACE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknowm error.
        /// </summary>
        public static string UNKNOWM_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown error.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The unlockedacessorystyles is required.
        /// </summary>
        public static string UNLOCKEDACESSORYSTYLES_REQUIRED {
            get {
                return ResourceManager.GetString("UNLOCKEDACESSORYSTYLES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The unlockedbagstyles is required.
        /// </summary>
        public static string UNLOCKEDBAGSTYLES_REQUIRED {
            get {
                return ResourceManager.GetString("UNLOCKEDBAGSTYLES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The unlockedheadstyles is required.
        /// </summary>
        public static string UNLOCKEDHEADSTYLES_REQUIRED {
            get {
                return ResourceManager.GetString("UNLOCKEDHEADSTYLES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The unlockedlegstyles is required.
        /// </summary>
        public static string UNLOCKEDLEGSTYLES_REQUIRED {
            get {
                return ResourceManager.GetString("UNLOCKEDLEGSTYLES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The unlockedmapstyles is required.
        /// </summary>
        public static string UNLOCKEDMAPSTYLES_REQUIRED {
            get {
                return ResourceManager.GetString("UNLOCKEDMAPSTYLES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The unlockedpointofintereststyles is required.
        /// </summary>
        public static string UNLOCKEDPOINTOFINTERESTSTYLES_REQUIRED {
            get {
                return ResourceManager.GetString("UNLOCKEDPOINTOFINTERESTSTYLES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The unlockedtorsostyles is required.
        /// </summary>
        public static string UNLOCKEDTORSOSTYLES_REQUIRED {
            get {
                return ResourceManager.GetString("UNLOCKEDTORSOSTYLES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update date cannot be in the past.
        /// </summary>
        public static string UPDATE_DATE_IN_THE_PAST {
            get {
                return ResourceManager.GetString("UPDATE_DATE_IN_THE_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not found.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relationship between users not found.
        /// </summary>
        public static string USER_RELATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_RELATION_NOT_FOUND", resourceCulture);
            }
        }
    }
}
